### ISSUE TITLE
Registering request specific behavior breaks pipeline if registered in wrong order

### ISSUE THREAD

**Issue by pillepalle1** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#117] opened 2022-03-03 15:25 UTC
I have implemented two pipeline behaviors. One is specific to a `GetMoneyRequest` while the other is to be applied to all requests. For the sake of argument let them be implemented as follows:

```
public class GetMoneyBehavior : IPipelineBehavior<GetMoneyRequest, GetMoneyResponse>
{
    private readonly ILogger<GetMoneyBehavior> _logger;

    public GetMoneyBehavior(ILogger<GetMoneyBehavior> logger)
    {
        _logger = logger;
    }

    public async Task<GetMoneyResponse> Handle(GetMoneyRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<GetMoneyResponse> next)
    {
        _logger.LogInformation($"{nameof(GetMoneyBehavior)}: Detected request for USD {request.Amount}");

        var result = await next();

        var approved = result.Approved ? "" : "not ";
        _logger.LogCritical($"{nameof(GetMoneyBehavior)}: Request for USD {request.Amount} was {approved}approved");

        return result;
    }
}

public class AllRequestsBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : MediatR.IRequest<TResponse>
{
    private readonly ILogger<AllRequestsBehavior<TRequest, TResponse>> _logger;

    public AllRequestsBehavior(ILogger<AllRequestsBehavior<TRequest, TResponse>> logger)
    {
        _logger = logger;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        _logger.LogInformation($"{nameof(AllRequestsBehavior<TRequest, TResponse>)} is pre-processing stuff");

        var result = await next();

        _logger.LogInformation($"{nameof(AllRequestsBehavior<TRequest, TResponse>)} is post-processing stuff");

        return result;
    }
}
```

If I register them as follows, then everything works fine and as expected.

```
builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(AllRequestsBehavior<,>));
builder.Services.AddTransient(typeof(IPipelineBehavior<GetMoneyRequest, GetMoneyResponse>), typeof(GetMoneyBehavior));
```

If however I register them in another order as this

```
builder.Services.AddTransient(typeof(IPipelineBehavior<GetMoneyRequest, GetMoneyResponse>), typeof(GetMoneyBehavior));
builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(AllRequestsBehavior<,>));
```

then for a `GetMoneyRequest` the handler in `GetMoneyBehavior` is executed twice, while the handler in `AllRequestsBehavior` is ignored. For all other requests however the handler in `AllRequestsBehavior` is invoked correctly.

**Comment by jbogard** [comment] 2022-03-04 02:55
This might be a variant of this bug: https://github.com/dotnet/runtime/issues/65145

Can you try resolving the enumerable of pipeline behaviors directly from the container? You can check the issue as a way to see how to write that test. MediatR just delegates to the container for resolution so this might be a new bug or variation of the linked one.

**Comment by pillepalle1** [comment] 2022-03-04 03:51
Done.

Tests can be found here: https://github.com/pillepalle1/aspnet-cheatsheets/blob/master/packages/MediatR.MinimalApi.Unit.Tests/DependencyInjectionTests.cs

Both tests succeed

![image](https://user-images.githubusercontent.com/30006468/156695939-7f41512b-f61e-42e5-8010-0e87d2540929.png)

**Comment by jbogard** [comment] 2022-03-04 16:21
Actually it's the same issue. I was able to remove MediatR from the equation entirely:

```csharp
public interface IMarker<T> {}
public class A : IMarker<B> { }
public class B { }

public interface IService<T, U> where T : IMarker<U>
{
    Task<U> Execute(T input, CancellationToken token, Func<Task<U>> next);
}

public class ConcreteService : IService<A, B>
{

    public async Task<B> Execute(A request, CancellationToken cancellationToken, Func<Task<B>> next)
    {
        var output = await next();

        return output;
    }
}

public class GenericService<T, U> : IService<T, U>
    where T : IMarker<U>
{
    public async Task<U> Execute(T input, CancellationToken cancellationToken, Func<Task<U>> next)
    {
        var output = await next();

        return output;
    }
}

[Fact]
public void Test_ConcreteBeforeOpenGenericAgainstBuilder_ShouldResolveServices()
{
    var args = new[]
    {
        "--environment=Development"
    };
    var builder = WebApplication.CreateBuilder(args);

    var services = builder.Services;

    services.AddTransient(
        typeof(IService<A, B>),
        typeof(ConcreteService));

    services.AddTransient(
        typeof(IService<,>),
        typeof(GenericService<,>));

    var app = builder.Build();

    var handlers = app.Services
        .GetServices<IService<A, B>>()
        .ToList();

    Assert.True(2 == handlers.Count);

    var handlerTypes = handlers
        .Select(h => h.GetType())
        .ToList();

    Assert.Contains(handlerTypes, e => e == typeof(ConcreteService));
    Assert.Contains(handlerTypes, e => e == typeof(GenericService<A, B>));
    Assert.True(handlerTypes[0] != handlerTypes[1]);
}

[Fact]
public void Test_GenericBeforeConcreteAgainstBuilder_ShouldResolveServices()
    {
        var args = new[]
        {
            "--environment=Development"
        };
        var builder = WebApplication.CreateBuilder(args);

        var services = builder.Services;

        services.AddTransient(
            typeof(IService<,>),
            typeof(GenericService<,>));

        services.AddTransient(
            typeof(IService<A, B>),
            typeof(ConcreteService));

        var app = builder.Build();

        var handlers = app.Services
            .GetServices<IService<A, B>>()
            .ToList();

        Assert.True(2 == handlers.Count);

        var handlerTypes = handlers
            .Select(h => h.GetType())
            .ToList();

        Assert.Contains(handlerTypes, e => e == typeof(ConcreteService));
        Assert.Contains(handlerTypes, e => e == typeof(GenericService<A, B>));
        Assert.True(handlerTypes[0] != handlerTypes[1]);
    }

[Fact]
public void Test_ConcreteBeforeOpenGenericAgainstServiceCollection_ShouldResolveServices()
{
    var services = new ServiceCollection();

    services.AddTransient(
        typeof(IService<A, B>),
        typeof(ConcreteService));

    services.AddTransient(
        typeof(IService<,>),
        typeof(GenericService<,>));

    var serviceProvider = services.BuildServiceProvider(new ServiceProviderOptions {ValidateOnBuild = true});

    var handlers = serviceProvider
        .GetServices<IService<A, B>>()
        .ToList();

    Assert.True(2 == handlers.Count);

    var handlerTypes = handlers
        .Select(h => h.GetType())
        .ToList();

    Assert.Contains(handlerTypes, e => e == typeof(ConcreteService));
    Assert.Contains(handlerTypes, e => e == typeof(GenericService<A, B>));
    Assert.True(handlerTypes[0] != handlerTypes[1]);
}

[Fact]
public void Test_GenericBeforeConcreteAgainstServiceCollection_ShouldResolveServices()
{
    var services = new ServiceCollection();

    services.AddTransient(
        typeof(IService<,>),
        typeof(GenericService<,>));

    services.AddTransient(
        typeof(IService<A, B>),
        typeof(ConcreteService));

    var serviceProvider = services.BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = true });

    var handlers = serviceProvider
        .GetServices<IService<A, B>>()
        .ToList();

    Assert.True(2 == handlers.Count);

    var handlerTypes = handlers
        .Select(h => h.GetType())
        .ToList();

    Assert.Contains(handlerTypes, e => e == typeof(ConcreteService));
    Assert.Contains(handlerTypes, e => e == typeof(GenericService<A, B>));
    Assert.True(handlerTypes[0] != handlerTypes[1]);
}
```

The tests that put the concrete one first fail. I validated this by changing the example app you created to `Production` and got this output:

```
info: MediatR.MinimalApi.SpecificPipelineBehavior.GetMoneyBehavior[0]
      GetMoneyBehavior: Detected request for USD 200
info: MediatR.MinimalApi.GeneralPipelineBehavior.AllRequestsBehavior[0]
      AllRequestsBehavior is pre-processing stuff
info: MediatR.MinimalApi.GeneralPipelineBehavior.AllRequestsBehavior[0]
      AllRequestsBehavior is post-processing stuff
crit: MediatR.MinimalApi.SpecificPipelineBehavior.GetMoneyBehavior[0]
      GetMoneyBehavior: Request for USD 200 was not approved
```

**Comment by jbogard** [comment] 2022-03-04 16:21
Duplicate of #118

**Closed by jbogard** 2022-03-04 16:21 UTC
